### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by rachmadaniHaryono** [sindresorhus/awesome-lint#18]
hi i got an error when running this on my travis

https://travis-ci.org/rachmadaniHaryono/awesome-django/builds/229557630

```
const meow = require('meow');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
The command "awesome-lint" exited with 8.
```
repo: https://github.com/rachmadaniHaryono/awesome-django

is there anything else i should include here?

**Comment by sindresorhus** [comment]
Upgrade Node.js
